Algoritmo "SomaBasica"

// Data atual  : 14/06/2025
Var
  nome:caractere
  N1, N2:real
  S:real



Inicio
  Escreval ("Hello, I can do some calcules for you!")
  Escreva ("But first of all, may you tell me your name?")
  Leia(nome)
  Escreval ("Oh, nice to meet you, ",nome)
  Escreva ("So, what do u want? send ")
   Se ("S") Escreva ("Oh, nice, and a number ?")
   Leia (N1)
  Escreva ("Good! and the next?")
   Leia (N2)
  S <- N1 + N2
  Escreva ("The result is:",S)
   

Fimalgoritmo