Algoritmo "ExercicioDeIdade"

// Data atual  : 16/06/2025
Var
   ano_atual, ano_nasc, idade:inteiro



Inicio
      Escreval("Espera, cê esqueceu em que ano nasceu?")
      Escreva("Posso te ajudar, só me fala em que ano estamos? ")
      Leia(ano_atual)
      Escreva("Agora me fala o ano que voce nasceu? ")
      Leia(ano_nasc)
      idade <- ano_atual - ano_nasc
      Escreva("Descobri! Voce tem ", idade, " anos")


Fimalgoritmo